[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "mkdir -p database",
    "touch database/database.sqlite",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan migrate --force"
]

[phases.start] 
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"