[phases.setup]
aptPkgs = ["default-mysql-client"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.deploy]
startCmd = "php artisan migrate --force && php -S 0.0.0.0:9000 -t public"