[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --optimize-autoloader && php artisan key:generate --force"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8080"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
start-phase = "web"